customhost = "mydatabase.czqs9igxojjk.us-east-1.rds.amazonaws.com"
customuser = "venugopal"
custompass = "Venugopal!123"
customdb = "employee"
custombucket = "mydbdatabase"
customregion = "us-east-1"
